"""rename the table from department to departments

Revision ID: 955af4a757bd
Revises: e5ee5a0fea14
Create Date: 2026-01-07 08:28:09.876682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955af4a757bd'
down_revision = 'e5ee5a0fea14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
 
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
