"""rename the address column

Revision ID: e755b2ac1c22
Revises: 955af4a757bd
Create Date: 2026-01-07 08:50:33.835950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e755b2ac1c22'
down_revision = '955af4a757bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', "address", new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', "location", new_column_name='address')
    # ### end Alembic commands ###
